# -*- coding: utf-8 -*-
"""EV_mkt_segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pz0ogVxk463177lmrARky5TG-BpnIabC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("data_1.csv")

df.head()

# Preprocesing
# Handling Missing Values
print("Missing Values Before Handling:\n", df.isnull().sum())

#identifying categorical and numerical columns
num_cols = df.select_dtypes(include = ["int64", "float64"]).columns
cat_cols = df.select_dtypes(include = ["object"]).columns

cat_cols

# increasing granularity
age_mapping = {"18-25": (18, 25), "26-35": (26, 35), "36-45": (36, 45), "46-60": (46, 60), "60+": (61, 80)}
df["Age_Numeric"] = df["Age_Group"].apply(lambda x: np.random.randint(age_mapping[x][0], age_mapping[x][1]+1))

income_mapping = {"Low": (10000, 30000), "Middle": (31000, 70000), "High": (71000, 150000)}
df["Income_Numeric"] = df["Income_Level"].apply(lambda x: np.random.randint(income_mapping[x][0], income_mapping[x][1]+1))


df.head()

# standard scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Apply scaling to Age_Numeric and Income_Numeric
df_scaled = scaler.fit_transform(df[["Age_Numeric", "Income_Numeric"]])

# Elbow Method
inertia = []  # List to store inertia values
K_range = range(2, 10)  # Testing k from 1 to 10

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(df_scaled)
    inertia.append(kmeans.inertia_)  # Store inertia for each k

# Plot the Elbow Graph
plt.figure(figsize=(8, 6))
plt.plot(K_range, inertia, marker="o", linestyle="--")
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia (Sum of Squared Distances)")
plt.title("Elbow Method for Optimal k")
plt.show()

# K-Means Clustering
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df["KMeans_Cluster"] = kmeans.fit_predict(df_scaled)

# Scatter plot of clusters
plt.figure(figsize=(15,10))
sns.scatterplot(x=df_scaled[:, 0], y=df_scaled[:, 1], hue=df["KMeans_Cluster"], palette="viridis")
plt.xlabel("Age (Scaled)")
plt.ylabel("Income (Scaled)")
plt.title("K-Means Clustering of Age and Income")
plt.show()

# Hiearchical Clustering
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.cluster import AgglomerativeClustering

X_hc = df_scaled

plt.figure(figsize=(15, 10))
dendrogram = sch.dendrogram(sch.linkage(X_hc, method='ward'))
plt.title("Dendrogram for Hierarchical Clustering")
plt.xlabel("Data Points")
plt.ylabel("Euclidean Distance")
plt.show()

optimal_clusters = 3
hc = AgglomerativeClustering(n_clusters=optimal_clusters, linkage='ward',metric='euclidean')
df['HC_Cluster'] = hc.fit_predict(X_hc)

#  Visualizing the Clusters
plt.figure(figsize=(15, 10))
for cluster in range(optimal_clusters):
    plt.scatter(X_hc[df['HC_Cluster'] == cluster, 0], X_hc[df['HC_Cluster'] == cluster, 1], label=f"Cluster {cluster}")

plt.title("Hierarchical Clustering of Age and Income")
plt.xlabel("Age (Scaled)")
plt.ylabel("Income (Scaled)")
plt.legend()
plt.show()

# DBSCAN
from sklearn.cluster import DBSCAN

X_dbscan = df_scaled
dbscan = DBSCAN(eps=0.3, min_samples=10)  # Adjust 'eps' based on data density
df['DBSCAN_Cluster'] = dbscan.fit_predict(X_dbscan)

unique_clusters = np.unique(df['DBSCAN_Cluster'])
print("Clusters Found:", unique_clusters)

#  Plot the Clusters
plt.figure(figsize=(15, 10))
for cluster in unique_clusters:
    if cluster == -1:
        plt.scatter(X_dbscan[df['DBSCAN_Cluster'] == cluster, 0], X_dbscan[df['DBSCAN_Cluster'] == cluster, 1],
                    color='red', label="Noise", marker="x")  # Mark noise
    else:
        plt.scatter(X_dbscan[df['DBSCAN_Cluster'] == cluster, 0], X_dbscan[df['DBSCAN_Cluster'] == cluster, 1],
                    label=f"Cluster {cluster}")

plt.title("DBSCAN Clustering of Age and Income")
plt.xlabel("Age (Scaled)")
plt.ylabel("Income (Scaled)")
plt.legend()
plt.show()

# bar plots

plt.figure(figsize=(8, 5))
sns.countplot(x=df["KMeans_Cluster"], palette="viridis")
plt.xlabel("Cluster")
plt.ylabel("Count")
plt.title("Distribution of Data Points Across Clusters")
plt.show()

plt.figure(figsize=(8, 5))
sns.countplot(x=df["HC_Cluster"], palette="viridis")
plt.xlabel("Cluster")
plt.ylabel("Count")
plt.title("Distribution of Data Points Across Clusters")
plt.show()

plt.figure(figsize=(8, 5))
sns.countplot(x=df["DBSCAN_Cluster"], palette="viridis")
plt.xlabel("Cluster")
plt.ylabel("Count")
plt.title("Distribution of Data Points Across Clusters")
plt.show()

# box plots
plt.figure(figsize=(12, 5))
sns.boxplot(x=df["KMeans_Cluster"], y=df["Age_Numeric"], palette="Set2")
plt.xlabel("Cluster")
plt.ylabel("Age")
plt.title("Age Distribution Across Clusters")
plt.show()

plt.figure(figsize=(12, 5))
sns.boxplot(x=df["KMeans_Cluster"], y=df["Income_Numeric"], palette="Set3")
plt.xlabel("Cluster")
plt.ylabel("Income")
plt.title("Income Distribution Across Clusters")
plt.show()

plt.figure(figsize=(12, 5))
sns.boxplot(x=df["HC_Cluster"], y=df["Age_Numeric"], palette="Set2")
plt.xlabel("Cluster")
plt.ylabel("Age")
plt.title("Age Distribution Across Clusters")
plt.show()

plt.figure(figsize=(12, 5))
sns.boxplot(x=df["HC_Cluster"], y=df["Income_Numeric"], palette="Set3")
plt.xlabel("Cluster")
plt.ylabel("Income")
plt.title("Income Distribution Across Clusters")
plt.show()

plt.figure(figsize=(12, 5))
sns.boxplot(x=df["DBSCAN_Cluster"], y=df["Age_Numeric"], palette="Set2")
plt.xlabel("Cluster")
plt.ylabel("Age")
plt.title("Age Distribution Across Clusters")
plt.show()

plt.figure(figsize=(12, 5))
sns.boxplot(x=df["DBSCAN_Cluster"], y=df["Income_Numeric"], palette="Set3")
plt.xlabel("Cluster")
plt.ylabel("Income")
plt.title("Income Distribution Across Clusters")
plt.show()

# heatmaps
numeric_cols = ["Age_Numeric", "Income_Numeric"]  # Add other relevant numeric features if needed
cluster_means = df.groupby("KMeans_Cluster")[numeric_cols].mean()

# Plot heatmap
plt.figure(figsize=(8, 5))
sns.heatmap(cluster_means.T, cmap="coolwarm", annot=True, fmt=".2f")
plt.title("Cluster Feature Heatmap")
plt.show()

# Selecting only numeric columns for aggregation
numeric_cols = ["Age_Numeric", "Income_Numeric"]  # Add other relevant numeric features if needed
cluster_means = df.groupby("HC_Cluster")[numeric_cols].mean()

# Plot heatmap
plt.figure(figsize=(8, 5))
sns.heatmap(cluster_means.T, cmap="coolwarm", annot=True, fmt=".2f")
plt.title("Cluster Feature Heatmap")
plt.show()

# Selecting only numeric columns for aggregation
numeric_cols = ["Age_Numeric", "Income_Numeric"]  # Add other relevant numeric features if needed
cluster_means = df.groupby("DBSCAN_Cluster")[numeric_cols].mean()

# Plot heatmap
plt.figure(figsize=(8, 5))
sns.heatmap(cluster_means.T, cmap="coolwarm", annot=True, fmt=".2f")
plt.title("Cluster Feature Heatmap")
plt.show()

# pairplots
sns.pairplot(df, hue="KMeans_Cluster", palette="viridis")
plt.show()

sns.pairplot(df, hue="HC_Cluster", palette="viridis")
plt.show()

sns.pairplot(df, hue="DBSCAN_Cluster", palette="viridis")
plt.show()

